### ISSUE TITLE
Select never finds if used not primary key

### ISSUE THREAD

**Issue by belazar13** [tarantool/tarantool-php#58]
I have such space
```
localhost:3301> s
---
- index:
    0: &0
      unique: true
      parts:
      - type: NUM
        fieldno: 1
      id: 0
      space_id: 514
      name: primary
      type: HASH
    1: &1
      unique: false
      parts:
      - type: NUM
        fieldno: 3
      id: 1
      space_id: 514
      name: secondary
      type: TREE
    primary: *0
    secondary: *1
  on_replace: 'function: 0xb6e432a0'
  temporary: false
  id: 514
  engine: memtx
  enabled: true
  name: tester
  field_count: 0
```
I have script ( i want find all rows less 10):
```
<?php
$tarantool = new Tarantool("localhost", 3301);
for ($i = 0; $i < 1000; $i++)
{
    $tarantool->insert("tester", array($i, uniqid(), $i));
}

$row = $tarantool->select('tester', 10);
$rows = $tarantool->select('tester', 10, 'secondary', null, null, 3);

// ITER_LT = 3
```
Variable $rows is always empty array.
```
PHP 5.5.9-1ubuntu4.14
```
